### ISSUE TITLE
Adobe API

### ISSUE THREAD

**Issue by hreikin** [hreikin/pdf-extract-adobe#8]
**Task List:**

- [x] Create request
- [x] Split Json to store in DB
- [x] Store targeted elements in DB
- [x] Iterate through nested items

**Comment by hreikin** [comment]
Task list complete, closing issue. Can be reopened if more features/tasks are required.
